#!/bin/bash
#
#    Copyright 2012 Joel Weinberger
#   
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#   
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#   
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

USAGE="$0 filesystem [snapshot prefix]"
DATEFORMAT="%Y-%m-%d-%H:%M"
PREFIX=""

if [[ "--help" == "$1" || "-h" == "$1" ]]; then
    echo $USAGE
    exit 0
fi

if [ "" != "$1" ]; then
	PREFIX="$1"
fi

if [ 0 == $# ]; then
    echo "You must provide at least one argument."
    echo $USAGE
    exit 0
fi

ZFSROOT=$1

if [ 1 != $# ]; then
    PREFIX="$2"
fi

SNAPNAME="$PREFIX`date +$DATEFORMAT`"
echo "Taking full snapshot of $ZFSROOT@$SNAPNAME"

sudo zfs snapshot -r $ZFSROOT@$SNAPNAME
